Uses sonar-scanner-cli-4.7.0.2747

diff --git a/bin/sonar-scanner b/bin/sonar-scanner
--- a/bin/sonar-scanner
+++ b/bin/sonar-scanner
@@ -1,34 +1,36 @@
-#!/bin/sh
+#!/usr/bin/env sh
 #
-# SonarQube Scanner Startup Script for Unix
+# SonarScanner Startup Script for Unix
+#
+# Required ENV vars:
+#   JAVA_HOME - Location of Java's installation, optional if use_embedded_jre is set
 #
 # Optional ENV vars:
-#   SONAR_SCANNER_OPTS - Parameters passed to the Java VM when running the SonarQube Scanner
+#   SONAR_SCANNER_OPTS - Parameters passed to the Java VM when running the SonarScanner
 #   SONAR_SCANNER_DEBUG_OPTS - Extra parameters passed to the Java VM for debugging
-#   JAVA_HOME - Location of Java's installation
 
 real_path () {
   target=$1
 
   (
   while true; do
-    cd "$(dirname "$target")"
-    target=$(basename "$target")
+    cd "`dirname "$target"`"
+    target=`basename "$target"`
     test -L "$target" || break
-    target=$(readlink "$target")
+    target=`readlink "$target"`
   done
 
-  echo "$(pwd -P)/$target"
+  echo "`pwd -P`/$target"
   )
 }
 
-script_path=$(real_path "$0")
-sonar_scanner_home=$(dirname "$script_path")/..
+script_path=`real_path "$0"`
+sonar_scanner_home=`dirname "$script_path"`/..
 
 # make it fully qualified
-sonar_scanner_home=$(cd "$sonar_scanner_home" && pwd -P)
+sonar_scanner_home=`cd "$sonar_scanner_home" && pwd -P`
 
-jar_file=$sonar_scanner_home/lib/sonar-scanner-cli-3.1.0.1141.jar
+jar_file=$sonar_scanner_home/lib/sonar-scanner-cli-4.7.0.2747.jar
 
 # check that sonar_scanner_home has been correctly set
 if [ ! -f "$jar_file" ] ; then
@@ -39,17 +41,22 @@ fi
 
 use_embedded_jre=false
 if [ "$use_embedded_jre" = true ]; then
-  export JAVA_HOME=$sonar_scanner_home/jre
+  export JAVA_HOME="$sonar_scanner_home/jre"
 fi
 
 if [ -n "$JAVA_HOME" ]
 then
   java_cmd="$JAVA_HOME/bin/java"
 else
-  java_cmd="$(which java)"
+  java_cmd="`which java`"
 fi
 
-project_home=$(pwd)
+if [ -z "$java_cmd" -o ! -x "$java_cmd" ] ; then
+  echo "Could not find 'java' executable in JAVA_HOME or PATH."
+  exit 1
+fi
+
+project_home=`pwd`
 
 #echo "Info: Using sonar-scanner at $sonar_scanner_home"
 #echo "Info: Using java at $java_cmd"
